language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.clone("git://github.com/davidavdav/HClust.jl"); Pkg.build("Augur"); Pkg.test("Augur"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Augur")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'